/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "accesoUsuarios.h"

bool_t
xdr_sigAdmin1 (XDR *xdrs, sigAdmin1 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct nodo_admin1), (xdrproc_t) xdr_nodo_admin1))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sigUsuario1 (XDR *xdrs, sigUsuario1 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct nodo_usuario1), (xdrproc_t) xdr_nodo_usuario1))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_admin1 (XDR *xdrs, nodo_admin1 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->login, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->clave, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_sigAdmin1 (xdrs, &objp->nodoSiguiente))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_usuario1 (XDR *xdrs, nodo_usuario1 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombres, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->apellidos, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->rol, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->codigo, 8,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_sigUsuario1 (xdrs, &objp->nodoSiguiente))
		 return FALSE;
	return TRUE;
}
