/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONTROLENTRADASALIDA_H_RPCGEN
#define _CONTROLENTRADASALIDA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct nodo_admin2 *sigAdmin2;

typedef struct nodo_usuario2 *sigUsuario2;

struct nodo_admin2 {
	char login[15];
	char clave[15];
	sigAdmin2 nodoSiguiente;
};
typedef struct nodo_admin2 nodo_admin2;

struct nodo_usuario2 {
	char nombres[50];
	char apellidos[50];
	char rol[15];
	char codigo[8];
	sigUsuario2 nodoSiguiente;
};
typedef struct nodo_usuario2 nodo_usuario2;

#define AdministrarControlEntradaSalida 0x20000003
#define AdministrarControlEntradaSalida1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ingresarSistema2 10
extern  bool_t * ingresarsistema2_1(sigAdmin2 *, CLIENT *);
extern  bool_t * ingresarsistema2_1_svc(sigAdmin2 *, struct svc_req *);
#define modificarAdmin2 11
extern  bool_t * modificaradmin2_1(sigAdmin2 *, CLIENT *);
extern  bool_t * modificaradmin2_1_svc(sigAdmin2 *, struct svc_req *);
#define consultarUsuariosDentro2 12
extern  sigUsuario2 * consultarusuariosdentro2_1(void *, CLIENT *);
extern  sigUsuario2 * consultarusuariosdentro2_1_svc(void *, struct svc_req *);
extern int administrarcontrolentradasalida_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ingresarSistema2 10
extern  bool_t * ingresarsistema2_1();
extern  bool_t * ingresarsistema2_1_svc();
#define modificarAdmin2 11
extern  bool_t * modificaradmin2_1();
extern  bool_t * modificaradmin2_1_svc();
#define consultarUsuariosDentro2 12
extern  sigUsuario2 * consultarusuariosdentro2_1();
extern  sigUsuario2 * consultarusuariosdentro2_1_svc();
extern int administrarcontrolentradasalida_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sigAdmin2 (XDR *, sigAdmin2*);
extern  bool_t xdr_sigUsuario2 (XDR *, sigUsuario2*);
extern  bool_t xdr_nodo_admin2 (XDR *, nodo_admin2*);
extern  bool_t xdr_nodo_usuario2 (XDR *, nodo_usuario2*);

#else /* K&R C */
extern bool_t xdr_sigAdmin2 ();
extern bool_t xdr_sigUsuario2 ();
extern bool_t xdr_nodo_admin2 ();
extern bool_t xdr_nodo_usuario2 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CONTROLENTRADASALIDA_H_RPCGEN */
