/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "controlEntradaSalida.h"

bool_t
xdr_sigAdmin2 (XDR *xdrs, sigAdmin2 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct nodo_admin2), (xdrproc_t) xdr_nodo_admin2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sigUsuario2 (XDR *xdrs, sigUsuario2 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct nodo_usuario2), (xdrproc_t) xdr_nodo_usuario2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_admin2 (XDR *xdrs, nodo_admin2 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->login, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->clave, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_sigAdmin2 (xdrs, &objp->nodoSiguiente))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_usuario2 (XDR *xdrs, nodo_usuario2 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombres, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->apellidos, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->rol, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->codigo, 8,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_sigUsuario2 (xdrs, &objp->nodoSiguiente))
		 return FALSE;
	return TRUE;
}
