/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "controlEntradaSalida.h"
#include "accesoUsuarios.h"
#include "usuario.h"

void
administraraccesousuarios_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	sigAdmin1  ingresarsistema1_1_arg;
	bool_t  *result_2;
	sigUsuario1  registrarusuario1_1_arg;
	bool_t  *result_3;
	sigAdmin1  modificaradmin1_1_arg;
	bool_t  *result_4;
	sigUsuario1  modificarusuario1_1_arg;
	bool_t  *result_5;
	char * borrarusuario1_1_arg;
	bool_t  *result_6;
	char * buscarusuario1_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, AdministrarAccesoUsuarios, AdministrarAccesoUsuarios1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = ingresarsistema1_1(&ingresarsistema1_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = registrarusuario1_1(&registrarusuario1_1_arg, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = modificaradmin1_1(&modificaradmin1_1_arg, clnt);
	if (result_3 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = modificarusuario1_1(&modificarusuario1_1_arg, clnt);
	if (result_4 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = borrarusuario1_1(&borrarusuario1_1_arg, clnt);
	if (result_5 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = buscarusuario1_1(&buscarusuario1_1_arg, clnt);
	if (result_6 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

bool_t *
ingresarsistema2_1_svc(sigAdmin2 *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */
	 

	return &result;
}

bool_t *
modificaradmin2_1_svc(sigAdmin2 *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

sigUsuario2 *
consultarusuariosdentro2_1_svc(void *argp, struct svc_req *rqstp)
{
	static sigUsuario2  result;

	/*
	 * insert server code here
	 */

	return &result;
}
