/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _USUARIO_H_RPCGEN
#define _USUARIO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define Usuario 0x20000001
#define Usuario1 1

#if defined(__STDC__) || defined(__cplusplus)
#define entrarALasInstalaciones 1
extern  bool_t * entraralasinstalaciones_1(char **, CLIENT *);
extern  bool_t * entraralasinstalaciones_1_svc(char **, struct svc_req *);
#define salirDeLasInstalaciones 2
extern  bool_t * salirdelasinstalaciones_1(char **, CLIENT *);
extern  bool_t * salirdelasinstalaciones_1_svc(char **, struct svc_req *);
#define esUsuarioRegistrado 3
extern  bool_t * esusuarioregistrado_1(char **, CLIENT *);
extern  bool_t * esusuarioregistrado_1_svc(char **, struct svc_req *);
extern int usuario_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define entrarALasInstalaciones 1
extern  bool_t * entraralasinstalaciones_1();
extern  bool_t * entraralasinstalaciones_1_svc();
#define salirDeLasInstalaciones 2
extern  bool_t * salirdelasinstalaciones_1();
extern  bool_t * salirdelasinstalaciones_1_svc();
#define esUsuarioRegistrado 3
extern  bool_t * esusuarioregistrado_1();
extern  bool_t * esusuarioregistrado_1_svc();
extern int usuario_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_USUARIO_H_RPCGEN */
