/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "usuario.h"


void
nodo_usuario_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	char * entrarinstalaciones_1_arg;
	bool_t  *result_2;
	char * salirinstalaciones_1_arg;
	bool_t  *result_3;
	char * esusuarioregistrado_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, nodo_usuario, Usuario1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = entrarinstalaciones_1(&entrarinstalaciones_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = salirinstalaciones_1(&salirinstalaciones_1_arg, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = esusuarioregistrado_1(&esusuarioregistrado_1_arg, clnt);
	if (result_3 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	nodo_usuario_1 (host);
exit (0);
}
