/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "controlEntradaSalida.h"


void
administrarcontrolentradasalida_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	loginAdmin  ingresoalsistema_1_arg;
	bool_t  *result_2;
	loginAdmin  modificardatosadmin_1_arg;
	void  *result_3;
	char *consultarusuariosdentroinstalaciones_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, AdministrarControlEntradaSalida, AdministrarControlEntradaSalida1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = ingresoalsistema_1(&ingresoalsistema_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = modificardatosadmin_1(&modificardatosadmin_1_arg, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = consultarusuariosdentroinstalaciones_1((void*)&consultarusuariosdentroinstalaciones_1_arg, clnt);
	if (result_3 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	administrarcontrolentradasalida_1 (host);
exit (0);
}
