/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "controlEntradaSalida.h"

bool_t
xdr_loginAdmin (XDR *xdrs, loginAdmin *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->login, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->clave, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
