/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONTROLENTRADASALIDA_H_RPCGEN
#define _CONTROLENTRADASALIDA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct loginAdmin {
	char login[15];
	char clave[15];
};
typedef struct loginAdmin loginAdmin;

#define AdministrarControlEntradaSalida 0x20000001
#define AdministrarControlEntradaSalida1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ingresoAlSistema 1
extern  bool_t * ingresoalsistema_1(loginAdmin *, CLIENT *);
extern  bool_t * ingresoalsistema_1_svc(loginAdmin *, struct svc_req *);
#define modificarDatosAdmin 2
extern  bool_t * modificardatosadmin_1(loginAdmin *, CLIENT *);
extern  bool_t * modificardatosadmin_1_svc(loginAdmin *, struct svc_req *);
#define consultarUsuariosDentroInstalaciones 3
extern  void * consultarusuariosdentroinstalaciones_1(void *, CLIENT *);
extern  void * consultarusuariosdentroinstalaciones_1_svc(void *, struct svc_req *);
extern int administrarcontrolentradasalida_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ingresoAlSistema 1
extern  bool_t * ingresoalsistema_1();
extern  bool_t * ingresoalsistema_1_svc();
#define modificarDatosAdmin 2
extern  bool_t * modificardatosadmin_1();
extern  bool_t * modificardatosadmin_1_svc();
#define consultarUsuariosDentroInstalaciones 3
extern  void * consultarusuariosdentroinstalaciones_1();
extern  void * consultarusuariosdentroinstalaciones_1_svc();
extern int administrarcontrolentradasalida_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_loginAdmin (XDR *, loginAdmin*);

#else /* K&R C */
extern bool_t xdr_loginAdmin ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CONTROLENTRADASALIDA_H_RPCGEN */
