/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONTROLENTRADASALIDA_H_RPCGEN
#define _CONTROLENTRADASALIDA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct nodo_admin *sigAdmin;

struct nodo_admin {
	char login[15];
	char clave[15];
	sigAdmin nodoSiguiente;
};
typedef struct nodo_admin nodo_admin;

#define AdministrarControlEntradaSalida 0x20000001
#define AdministrarControlEntradaSalida1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ingresarSistema 1
extern  bool_t * ingresarsistema_1(sigAdmin *, CLIENT *);
extern  bool_t * ingresarsistema_1_svc(sigAdmin *, struct svc_req *);
#define modificarAdmin 2
extern  bool_t * modificaradmin_1(sigAdmin *, CLIENT *);
extern  bool_t * modificaradmin_1_svc(sigAdmin *, struct svc_req *);
#define consultarUsuariosDentro 3
extern  sigAdmin * consultarusuariosdentro_1(void *, CLIENT *);
extern  sigAdmin * consultarusuariosdentro_1_svc(void *, struct svc_req *);
extern int administrarcontrolentradasalida_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ingresarSistema 1
extern  bool_t * ingresarsistema_1();
extern  bool_t * ingresarsistema_1_svc();
#define modificarAdmin 2
extern  bool_t * modificaradmin_1();
extern  bool_t * modificaradmin_1_svc();
#define consultarUsuariosDentro 3
extern  sigAdmin * consultarusuariosdentro_1();
extern  sigAdmin * consultarusuariosdentro_1_svc();
extern int administrarcontrolentradasalida_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sigAdmin (XDR *, sigAdmin*);
extern  bool_t xdr_nodo_admin (XDR *, nodo_admin*);

#else /* K&R C */
extern bool_t xdr_sigAdmin ();
extern bool_t xdr_nodo_admin ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CONTROLENTRADASALIDA_H_RPCGEN */
