/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ACCESOUSUARIOS_H_RPCGEN
#define _ACCESOUSUARIOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct loginAdmin {
	char login[15];
	char clave[15];
};
typedef struct loginAdmin loginAdmin;

struct registrarUsuario {
	char nombres[50];
	char apellidos[50];
	char rol[15];
	char codigo[8];
};
typedef struct registrarUsuario registrarUsuario;

#define AdministrarAccesoUsuarios 0x20000001
#define AdministrarAccesoUsuarios1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ingresoAlSistema 1
extern  bool_t * ingresoalsistema_1(loginAdmin *, CLIENT *);
extern  bool_t * ingresoalsistema_1_svc(loginAdmin *, struct svc_req *);
#define registroUsuario 2
extern  bool_t * registrousuario_1(registrarUsuario *, CLIENT *);
extern  bool_t * registrousuario_1_svc(registrarUsuario *, struct svc_req *);
#define modificarDatosAdmin 3
extern  bool_t * modificardatosadmin_1(loginAdmin *, CLIENT *);
extern  bool_t * modificardatosadmin_1_svc(loginAdmin *, struct svc_req *);
#define modificarDatosUsuario 4
extern  bool_t * modificardatosusuario_1(registrarUsuario *, CLIENT *);
extern  bool_t * modificardatosusuario_1_svc(registrarUsuario *, struct svc_req *);
#define borrarRegistroUsuario 5
extern  bool_t * borrarregistrousuario_1(char **, CLIENT *);
extern  bool_t * borrarregistrousuario_1_svc(char **, struct svc_req *);
#define buscarUsuario 6
extern  bool_t * buscarusuario_1(char **, CLIENT *);
extern  bool_t * buscarusuario_1_svc(char **, struct svc_req *);
extern int administraraccesousuarios_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ingresoAlSistema 1
extern  bool_t * ingresoalsistema_1();
extern  bool_t * ingresoalsistema_1_svc();
#define registroUsuario 2
extern  bool_t * registrousuario_1();
extern  bool_t * registrousuario_1_svc();
#define modificarDatosAdmin 3
extern  bool_t * modificardatosadmin_1();
extern  bool_t * modificardatosadmin_1_svc();
#define modificarDatosUsuario 4
extern  bool_t * modificardatosusuario_1();
extern  bool_t * modificardatosusuario_1_svc();
#define borrarRegistroUsuario 5
extern  bool_t * borrarregistrousuario_1();
extern  bool_t * borrarregistrousuario_1_svc();
#define buscarUsuario 6
extern  bool_t * buscarusuario_1();
extern  bool_t * buscarusuario_1_svc();
extern int administraraccesousuarios_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_loginAdmin (XDR *, loginAdmin*);
extern  bool_t xdr_registrarUsuario (XDR *, registrarUsuario*);

#else /* K&R C */
extern bool_t xdr_loginAdmin ();
extern bool_t xdr_registrarUsuario ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ACCESOUSUARIOS_H_RPCGEN */
