/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ACCESOUSUARIOS_H_RPCGEN
#define _ACCESOUSUARIOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct nodo_admin1 *sigAdmin1;

typedef struct nodo_usuario1 *sigUsuario1;

struct nodo_admin1 {
	char login[15];
	char clave[15];
	sigAdmin1 nodoSiguiente;
};
typedef struct nodo_admin1 nodo_admin1;

struct nodo_usuario1 {
	char nombres[50];
	char apellidos[50];
	char rol[15];
	char codigo[8];
	sigUsuario1 nodoSiguiente;
};
typedef struct nodo_usuario1 nodo_usuario1;

#define AdministrarAccesoUsuarios 0x20000002
#define AdministrarAccesoUsuarios1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ingresarSistema1 4
extern  bool_t * ingresarsistema1_1(sigAdmin1 *, CLIENT *);
extern  bool_t * ingresarsistema1_1_svc(sigAdmin1 *, struct svc_req *);
#define registrarUsuario1 5
extern  bool_t * registrarusuario1_1(sigUsuario1 *, CLIENT *);
extern  bool_t * registrarusuario1_1_svc(sigUsuario1 *, struct svc_req *);
#define modificarAdmin1 6
extern  bool_t * modificaradmin1_1(sigAdmin1 *, CLIENT *);
extern  bool_t * modificaradmin1_1_svc(sigAdmin1 *, struct svc_req *);
#define modificarUsuario1 7
extern  bool_t * modificarusuario1_1(sigUsuario1 *, CLIENT *);
extern  bool_t * modificarusuario1_1_svc(sigUsuario1 *, struct svc_req *);
#define borrarUsuario1 8
extern  bool_t * borrarusuario1_1(char **, CLIENT *);
extern  bool_t * borrarusuario1_1_svc(char **, struct svc_req *);
#define buscarUsuario1 9
extern  bool_t * buscarusuario1_1(char **, CLIENT *);
extern  bool_t * buscarusuario1_1_svc(char **, struct svc_req *);
extern int administraraccesousuarios_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ingresarSistema1 4
extern  bool_t * ingresarsistema1_1();
extern  bool_t * ingresarsistema1_1_svc();
#define registrarUsuario1 5
extern  bool_t * registrarusuario1_1();
extern  bool_t * registrarusuario1_1_svc();
#define modificarAdmin1 6
extern  bool_t * modificaradmin1_1();
extern  bool_t * modificaradmin1_1_svc();
#define modificarUsuario1 7
extern  bool_t * modificarusuario1_1();
extern  bool_t * modificarusuario1_1_svc();
#define borrarUsuario1 8
extern  bool_t * borrarusuario1_1();
extern  bool_t * borrarusuario1_1_svc();
#define buscarUsuario1 9
extern  bool_t * buscarusuario1_1();
extern  bool_t * buscarusuario1_1_svc();
extern int administraraccesousuarios_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sigAdmin1 (XDR *, sigAdmin1*);
extern  bool_t xdr_sigUsuario1 (XDR *, sigUsuario1*);
extern  bool_t xdr_nodo_admin1 (XDR *, nodo_admin1*);
extern  bool_t xdr_nodo_usuario1 (XDR *, nodo_usuario1*);

#else /* K&R C */
extern bool_t xdr_sigAdmin1 ();
extern bool_t xdr_sigUsuario1 ();
extern bool_t xdr_nodo_admin1 ();
extern bool_t xdr_nodo_usuario1 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ACCESOUSUARIOS_H_RPCGEN */
