/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "accesoUsuarios.h"

bool_t
xdr_sigAdmin (XDR *xdrs, sigAdmin *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct nodo_admin), (xdrproc_t) xdr_nodo_admin))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sigUsuario (XDR *xdrs, sigUsuario *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct nodo_usuario), (xdrproc_t) xdr_nodo_usuario))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_admin (XDR *xdrs, nodo_admin *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->login, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->clave, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_sigAdmin (xdrs, &objp->nodoSiguiente))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_usuario (XDR *xdrs, nodo_usuario *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombres, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->apellidos, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->rol, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->codigo, 8,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_sigUsuario (xdrs, &objp->nodoSiguiente))
		 return FALSE;
	return TRUE;
}
