/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "accesoUsuarios.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
administraraccesousuarios_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		sigAdmin1 ingresarsistema1_1_arg;
		sigUsuario1 registrarusuario1_1_arg;
		sigAdmin1 modificaradmin1_1_arg;
		sigUsuario1 modificarusuario1_1_arg;
		char *borrarusuario1_1_arg;
		char *buscarusuario1_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case ingresarSistema1:
		_xdr_argument = (xdrproc_t) xdr_sigAdmin1;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) ingresarsistema1_1_svc;
		break;

	case registrarUsuario1:
		_xdr_argument = (xdrproc_t) xdr_sigUsuario1;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) registrarusuario1_1_svc;
		break;

	case modificarAdmin1:
		_xdr_argument = (xdrproc_t) xdr_sigAdmin1;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) modificaradmin1_1_svc;
		break;

	case modificarUsuario1:
		_xdr_argument = (xdrproc_t) xdr_sigUsuario1;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) modificarusuario1_1_svc;
		break;

	case borrarUsuario1:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) borrarusuario1_1_svc;
		break;

	case buscarUsuario1:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) buscarusuario1_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (AdministrarAccesoUsuarios, AdministrarAccesoUsuarios1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, AdministrarAccesoUsuarios, AdministrarAccesoUsuarios1, administraraccesousuarios_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (AdministrarAccesoUsuarios, AdministrarAccesoUsuarios1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, AdministrarAccesoUsuarios, AdministrarAccesoUsuarios1, administraraccesousuarios_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (AdministrarAccesoUsuarios, AdministrarAccesoUsuarios1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
